### ISSUE TITLE
Splitting arrays

### ISSUE THREAD

**Issue by kellermac** [daler/metaseq#19]
I have been enjoying using your program, thank you for all the great work and support. 

I have made some heat maps of MNase reads centred around the binding site of my favourite TF. I then sorted the sights based on density of reads. I want to investigate the "enriched" sites. Is there a way to split the array (in quartiles perhaps) and group the sorted sites into new gff files? Any advice would be greatly appreciated! -Keller

**Comment by daler** [comment]
The original, unsorted array retains the sort order of the features you used to generate it. So it becomes a numpy indexing exercise to get the indexes of the ranked rows of interest and extract them from the original features.

The most efficient way to get multiple separated features is probably to convert your features into a pandas dataframe (rather than use individual integer indexes into a pybedtools.BedTool object)

I'm making a bunch of assumptions about the nature of your data here, but something along these lines should work:

```python
import pybedtools
import numpy as np

# assume `a` is the unsorted array, then these are the indexes 
# of the rows ranked from highest to lowest row mean
ranked = np.argsort(a.mean(axis=1))[::-1]

# assume "myfeatures.bed" was what you used to create the array
features = pybedtools.BedTool('myfeatures.bed')

# double-check lengths match
assert len(features) == len(a)

# if you had a header in your bed file, might need to check the dataframe
df = features.to_dataframe()
df.head()

# dataframe rows of the 10 highest-row-mean features
df.iloc[ranked[:10]]

# output them to BED
df.iloc[ranked[:10]].to_csv('top10.bed', sep='\t', index=False, header=False)

```

**Comment by kellermac** [comment]
Thanks for pointing me in the right direction. Using your instruction I split my gff file into three sorted gffs. However somewhere along the way my START and END coordinates added an extra sig fig behind the decimal (.0 for all). gffutils.create_db doesn't like this, it wants intergers. Any idea which function is causing this?

**Comment by daler** [comment]
Sorry, I missed your response here somehow.

It's probably pandas.DataFrame that's casting to float. Try `df['start']=df['start'].astype(int)` and `df['end']=df['end'].astype(int)`. I'll look into pybedtools handling the type conversion automatically for cases like this where you need to export back to BED/GFF format.
